<template>
  <div id="app">
      <h2 style="text-align: center; margin-top: 1rem;">Kullanım Koşulları</h2>
      <hr/>
      
      <div style="width: 90%; margin-left: 4rem;">
          <p>
              1. Taraflar
İşbu kullanıcı sözleşmesi ("Kullanıcı Sözleşmesi"),
a) "Notesity" mobil uygulaması ("Notesity") üzerinden faaliyetlerini yürüten,
b) Notesity mobil uygulamasına üye olan uygulama kullanıcısı ("Üye")
arasında akdedilmiştir.
Şahıs ve Üye münferiden "Taraf", müştereken "Taraflar" olarak anılacaktır.
2. Sözleşmenin Amacı ve Konusu
2.1. İşbu Sözleşme’nin konusu Şahıs’ın sahip olduğu Notesity mobil uygulamasından Üye’nin faydalanma şartlarının belirlenmesidir.
2.2. Şahıs, Notesity uygulamasını işletmekle birlikte 6563 sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun uyarınca aracı hizmet sağlayıcı ve 5651 sayılı İnternet Ortamında Yapılan Yayınların Düzenlenmesi ve Bu Yayınlar Yoluyla İşlenen Suçlarla Mücadele Edilmesi Hakkında Kanun uyarınca yer sağlayıcıdır.
2.3. Şahıs, Üye’nin Notesity üzerinde yer alan not Alıcı ve Satıcı ile Üye arasında satış ilişkisinin kurulabilmesi için uygun elektronik ortamı sağlamaktadır.
2.4. Üye, Kullanıcı Sözleşmesi uyarınca Notesity’ye üye olmak, Şahıs tarafından sunulan hizmetlerden faydalanmak ve Notesity üzerinde Satıcılar ile gerçekleştirilecek ürün ve/veya hizmetleri satın almak istemektedir.
2.5. Kullanıcı Sözleşmesi’nin amacı, Üye’nin hizmetlerden yararlanmasına ilişkin koşulların belirlenmesi ve bu doğrultuda Taraflar’ın hak ve yükümlülüklerinin tespitidir.
2.6. Kullanıcı Sözleşmesi’nin Üye tarafından kabulü ile Üye, Notesity’de yer alan ve yer alacak olan hizmetlere, kullanıma, içeriklere ve Üye’ye yönelik her türlü beyanı da kabul etmiş olduğunu beyan ve taahhüt eder.
2.7. Herhangi bir şüpheye mahal vermemek adına belirtilmelidir ki, Üye ve Satıcılar arasındaki ilişki işbu Kullanıcı Sözleşmesi’nin kapsamına girmemekte olup Şahıs, Üye ve Satıcılar arasındaki ilişkiden hiçbir şekilde sorumlu değildir.
3. Tarafların Hak ve Yükümlülükleri
3.1. Üye’nin Notesity üzerinden “üyelik” sıfatının kazanarak hizmetlerden faydalanabilmesi, Üye’nin işbu Kullanıcı Sözleşmesi’nin onaylanmasına ve doğru ve güncel kişisel ve diğer sair bilgilerin verilerek üyelik işlemlerinin tamamlanmasına bağlıdır. Üye, verdiği bilgilerin kanunlar önünde doğru olduğunu, Şahıs’ın bu bilgilerin gerçeğe aykırılığı nedeniyle uğrayacağı tüm zararları aynen ve derhal tazmin edeceğini beyan ve taahhüt eder.
3.2. Üyelik işlemleri için ihtiyaç duyulan kullanıcı adı ve şifresi bizzat Üye tarafından oluşturulmakta olup söz konusu bilgilerin güvenliğinin ve gizliliğinin sağlanması kendi sorumluluğundadır. Üye’ye ait kullanıcı adı ve şifre ile gerçekleştirilen tüm işlemler Üye tarafından gerçekleştirilmiş kabul edilecek olup Üye, gerçekleştirilen iş ve işlemlerin kendisi tarafından gerçekleştirilmediği yolunda herhangi bir def’i ve/veya itiraz ileri süremeyecek ve/veya bu def’i veya itiraza dayanarak yükümlülüklerini yerine getirmekten kaçınamayacaktır. Bu sebeple üçüncü kişiler veya yetkili merciler tarafından Şahıs’e karşı ileri sürülebilecek tüm iddia ve taleplere karşı, Şahıs’in Üye’ye rücu hakkı söz konusu olup izinsiz kullanımdan kaynaklanan her türlü tazminat ve sair talep hakkı saklıdır.
3.3. Taraflar, Şahıs’in Notesity’da yer alan ve/veya Satıcı tarafından sağladığı herhangi bir ürün veya hizmetin satıcısı konumunda olmadığını, 6563 sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun uyarınca yalnızca "aracı hizmet sağlayıcı" ve 5651 sayılı İnternet Ortamında Yapılan Yayınların Düzenlenmesi ve Bu Yayınlar Yoluyla İşlenen Suçlarla Mücadele Edilmesi Hakkında Kanun uyarınca "yer sağlayıcı" olarak kabul edildiğini ve bu sebeple Notesity üzerinde yer alan ve Şahıs tarafından yayınlanmamış içeriğe ilişkin bir sorumluluğunun bulunmadığını ve söz konusu içeriğin hukuka uygun olup olmadığını kontrol etme gibi bir yükümlülüğünün bulunmadığını kabul, beyan ve taahhüt ederler.
3.4. Üye, Notesity üzerinden kendi seçeceği Satıcı(lar) ile Satıcı(lar)’ın not alışverişini sağlar. Söz konusu alım işlemi için akdedilecek mesafeli satış sözleşmelerinde Satıcı’nın satıcı taraf, kendisinin ise alıcı taraf olduğunu; Şahıs’in ise bahsi geçen mesafeli satış sözleşmesi ilişkisinde taraf olmadığını kabul ve beyan eder. Dolayısıyla Notesity üzerinden gerçekleştirilecek alım işlemlerinde sadece Satıcı’nın yürürlükteki tüketici hukuku mevzuatı ve sair mevzuat kapsamında her anlamda bizzat sorumlu olduğunu, Notesity üzerinde sergilenen ve/veya Satıcı tarafından sağlanan görsellerin, görseli sağlanan tüm ürünlerin kalitesinden, mevzuata uygunluğundan, garanti belgesi verilmesinden, faturalandırılmasından ve sair diğer gerekli belgenin tesliminden ve satış sonrası gereksinim duyulan servis vs. hizmetlerinden ve ürünlerin süresinde teslim edilmesinden yalnızca ilgili Satıcı’nın sorumlu olduğunu kabul ve beyan eder.
3.5. Taraflar, Üye ve Satıcı arasında gerçekleştirilen alışveriş üzerinde herhangi bir şekilde kamu düzenine ve genel ahlaka aykırı görsel ve yazılı beyan, içerik ve sözden Notesity’nin sorumlu olmadığını, uğrayacakları maddi ve manevi tüm zararlardan Notesity’i ari tutacaklarını kabul, beyan ve taahhüt ederler.
3.6. Üye, Satıcı ile yalnızca Satıcı’nın mesai saatleri içerisinde iletişim kurabileceğinin farkında olup, mücbir sebep dahil ancak bununla sınırlı olmamak üzere Satıcı’dan kaynaklanan herhangi bir aksama sebebiyle hizmet alamama durumunda Şahıs’ın herhangi bir şekilde ve surette sorumlu olmayacağını kabul ve beyan eder.
3.7. Üye, Notesity üzerinden sunulan hizmetlere erişim ve bunların kalitesinin büyük ölçüde ilgili internet servis sağlayıcısından temin edilen hizmetin kalitesine dayandığını ve söz konusu hizmet kalitesinden kaynaklı sorunlarda Şahıs’in herhangi bir sorumluluğunun bulunmadığını, Notesity’nin işleyişinin kusurdan ari olmadığını ve zaman zaman teknik aksaklıklar veya erişim engelleriyle karşılaşabileceğini bildiğini kabul ve beyan eder.
3.8. Üye, Notesity’yi kullanırken yasal mevzuat hükümlerine riayet etmeyi ve bunları ihlal etmemeyi baştan kabul ve taahhüt eder. Aksi takdirde, doğacak tüm hukuki ve cezai yükümlülükler tamamen ve münhasıran Üye’yi bağlayacaktır.
3.9. Üye, Notesity’yi hiçbir şekilde kamu düzenini bozucu, genel ahlaka aykırı, başkalarını rahatsız ve taciz edici şekilde, yasalara aykırı bir amaç için, başkalarının fikri ve telif haklarına tecavüz edecek şekilde kullanamaz.
3.10. Ayrıca Üye, başkalarının hizmetleri kullanmasını önleyici veya zorlaştırıcı faaliyet (spam, virus, truva atı, vb.) işlemlerde bulunamaz ve Notesity’nin tamamını veya bir bölümünü bozma, değiştirme veya ters mühendislik yapma amacıyla kullanamaz.
3.11. Üye’nin Notesity üzerinde Satıcı ve Satıcı’dan aldığı ürün ve hizmetlere ilişkin beyan ettiği, yazdığı fikir ve düşünceler, tamamen kendi kişisel görüşleridir. Bu görüş ve düşüncelerin Şahıs ile hiçbir ilgi ve bağlantısı olmayıp Şahıs’in Üye’nin beyan edeceği bu fikir ve görüşler nedeniyle üçüncü kişilerin uğrayabileceği zararlardan ve üçüncü kişilerin beyan edeceği fikir ve görüşler nedeniyle Üye’nin uğrayabileceği zararlardan dolayı herhangi bir sorumluluğu bulunmamaktadır. Şahıs’in yer sağlayıcı sıfatı ile Üye tarafından yapılan fikir ve görüşlerin içeriklerini kontrol etme gibi bir yükümlülüğü olmamasına rağmen, takdiri tamamen kendisine ait olmak üzere, söz konusu içeriği dileği zaman kontrol etme ve gerekli görürse erişime kapatma ve silme hakkına sahiptir. Notesity’de yayınladığı herhangi bir görsel, yazılı ve sair içerikle Şahıs’in ya da üçüncü kişilerin haklarını ihlal eden kişiler, Şahıs’e ve/veya söz konusu üçüncü kişilere karşı sorumludur.
3.12. Şahıs, Üye verilerinin yetkisiz kişilerce okunmasından ve Üye yazılım ve verilerine gelebilecek zararlardan dolayı sorumlu olmayacaktır. Üye, Notesity’nin kullanılmasından dolayı uğrayabileceği herhangi bir zarar yüzünden Şahıs’tan tazminat talep etmemeyi peşinen kabul, beyan ve taahhüt etmiştir.
3.13. Taraflar, Şahıs’in herhangi bir zamanda kendi takdirinde olmak üzere Üye’nin üyeliğini silme, Üye’ye ait dosya, belge ve bilgileri silme hakkı olduğunu ve bu durumda, Şahıs’in herhangi bir sorumluluğunun olmayacağını kabul, beyan ve taahhüt ederler.
3.14. Üye, Notesity’nin yazılım ve tasarımının Şahıs’in mülkiyetinde olduğunu ve bunlara ilişkin telif hakkı ve/veya diğer fikri mülkiyet haklarının ilgili kanunlarca korunduğunu ve bunların kendisi tarafından izinsiz kullanılamayacağını, iktisap edilemeyeceğini ve değiştirilemeyeceğini kabul ve beyan eder. Notesity’de yer alan Satıcılar’a ilişkin isim ve semboller sahiplerinin ticari markalarıdır ve ayrıca fikri mülkiyet hakları kapsamında korunmaktadır.
3.15. Şahıs, Notesity’nin iyileştirilmesi, geliştirilmesine yönelik olarak ve/veya yasal mevzuat çerçevesinde uygulamaya erişmek için kullanılan İnternet servis sağlayıcısının adı ve İnternet Protokol (IP) adresi, uygulamaya erişilen tarih ve saat gibi birtakım bilgiler toplanabilir.
3.16. Şahıs, uygulamanın içeriğini dilediği zaman değiştirme, kullanıcılara sağlanan herhangi bir hizmeti değiştirme ya da sona erdirme hakkını saklı tutar.
3.17. Şahıs, Üye’nin Notesity’de sunulan hizmetlerden yararlanabilmek için uygulama üzerinden kendisine sağladığı kişisel verilerin 6698 sayılı Kişisel Verilerin Korunması Kanunu da dahil her türlü mevzuata uygun bir şekilde işlenmesine, güvenliğinin sağlanmasına ve korunmasına önem vermektedir. Şahıs, bu kapsamda Üye’nin sağladığı kişisel verileri Notesity’de yer alan Gizlilik ve Kişisel Verilerin Korunması Politikası’na uygun olarak toplamakta, kullanmakta, aktarmakta ve diğer şekillerde işleyebilmektedir.
3.18. Şahıs, yürürlükteki mevzuat uyarınca yetkili makamların talebi halinde, Üye’nin kendisinde bulunan bilgilerini 6698 sayılı Kişisel Verilerin Korunması Kanunu uyarınca gerekli olduğu takdirde Üye’yi önceden bilgilendirmek suretiyle ve her durumda veri aktarım kurallarına tabi olarak söz konusu makamlarla paylaşabilecektir.
3.19. Şahıs, Notesity’nin virüs ve benzeri amaçlı yazılımlardan arındırılmış olması için mevcut imkanlar dahilinde tedbir almıştır. Nihai güvenliğin sağlanması için, Şahıs’ın söz konusu tedbirlerinin yanında Üye’nin gerekli korunmayı sair şekillerde sağlaması gerekmektedir. Bu bağlamda Üye, Notesity’nin kullanılmasıyla, kendi elektronik cihazının yazılım ve işletim sistemlerinde oluşabilecek tüm hata ve bunların doğrudan ya da dolaylı sonuçlarından kendisinin sorumlu olduğunu kabul ve beyan etmektedir.
3.20. Şahıs, işbu Kullanıcı Sözleşmesi uyarınca, Üye’nin kendisinde kayıtlı elektronik posta adreslerine bilgilendirme mailleri ve cep telefonlarına bilgilendirme SMS’leri gönderme yetkisine sahip olmakla beraber, Üye işbu Kullanıcı Sözleşmesi’ni onaylamakla birlikte bilgilendirme maillerinin elektronik posta adresine ve bilgilendirme SMS’lerinin cep telefonuna gönderilmesini kabul etmiş sayılacaktır.
3.21. Üye, ödeme yöntemine, üyeliğine ve siparişine ilişkin bilgilerin, ödemenin gerçekleştirilebilmesi ve ödeme usulsüzlüklerinin önlenmesi, araştırılması ve tespit edilmesini temin amacıyla paytr Ödeme Hizmetleri A.Ş.’ye aktarılmasına ve paytr tarafından https://www.paytr.com/gizlilik-politikasi adresindeki Gizlilik Politikası’nın en güncel halinde açıklandığı şekilde işlenmesine ve saklanmasına rıza göstermektedir.
4. Sözleşmenin Feshi
4.1. Taraflar’dan her biri, işbu Kullanıcı Sözleşmesi’ni tek taraflı olarak ve tazminat ödemeksizin her zaman feshedilebilir.
4.2. Şahıs, Üye’nin işbu Kullanıcı Sözleşmesi’nin herhangi bir hükmünü ihlal etmesi durumunda Üye’nin üyeliğini iptal ederek Kullanıcı Sözleşmesi’ni tek taraflı olarak feshedebilecektir.
5. Muhtelif Hükümler
5.1. Üye’nin, üyelik kaydı yapması Üye’nin Kullanıcı Sözleşmesi’nde yer alan tüm maddeleri okuduğu ve Kullanıcı Sözleşmesi’nde yer alan maddeleri kabul ettiği anlamına gelir. İşbu Kullanıcı Sözleşmesi, Üye’nin üye olması anında akdedilmiş ve karşılıklı olarak yürürlülüğe girmiştir.
5.2. Şahıs, işbu Kullanıcı Sözleşmesi’nin hüküm ve koşullarını herhangi bir şekilde ön ihbara ve/veya ihtara gerek olmaksızın her zaman değiştirebilir, güncelleyebilir veya iptal edebilir. Değiştirilen, güncellenen ya da yürürlükten kaldırılan her hüküm, yayın tarihinde tüm üyeler bakımından hüküm ifade edecektir.
5.3. Taraflar, Şahıs’e ait resmi defter ve ticari kayıtları ile Şahıs’in veri tabanında, sunucularında tutulan e-arşiv kayıtlarının, elektronik bilgilerin, elektronik yazışmaların ve bilgisayar kayıtlarının, bağlayıcı, kesin ve münhasır delil olarak, HUMK madde 287'ye uygun şekilde esas alınacağını ve söz konusu kayıtların bir delil sözleşmesi teşkil ettiği hususunu kabul ve beyan eder.
5.4. Şahıs, Üye’nin kaydolurken bildirmiş olduğu elektronik posta adresi vasıtasıyla veya telefon numarasına arama yapmak ve SMS göndermek suretiyle kendisi ile iletişim kuracaktır. Üye, elektronik posta adresi ve telefon numarasında değişiklik olması halinde Notesity üzerinden üye bilgilerini güncellemekle tutmakla yükümlüdür.
5.5. İşbu Kullanıcı Sözleşmesi’nin herhangi bir hükmünün yetkili herhangi bir mahkeme, tahkim heyeti veya idari makam tarafından tümüyle veya kısmen geçersiz veya uygulanamaz olduğu veya makul olmadığına karar verilmesi halinde, söz konusu geçersizlik, uygulanamazlık veya makul olmama ölçüsünde işbu Kullanıcı Sözleşmesi bölünebilir olarak kabul edilecek ve diğer hükümler tümüyle yürürlükte kalmaya devam edecektir.
5.6. Ayaklanma, ambargo, devlet müdahalesi, isyan, işgal, savaş, seferberlik, grev, lokavt, iş eylemleri veya boykotlar dahil olmak üzere işçi-işveren anlaşmazlıkları, siber saldırı, iletişim sorunları, altyapı ve internet arızaları, sisteme ilişkin iyileştirme veya yenileştirme çalışmaları ve bu sebeple meydana gelebilecek arızalar, elektrik kesintisi, yangın, patlama, fırtına, sel, deprem, göç, salgın hastalık veya diğer bir doğal felaket veya Şahıs’in kontrolü dışında gerçekleşen, kusurundan kaynaklanmayan ve makul olarak öngörülemeyecek diğer olaylar ("Mücbir Sebep") Şahıs’in işbu Kullanıcı Sözleşmesi’nden doğan yükümlülüklerini ifa etmesini engeller veya geciktirirse, Şahıs ifası Mücbir Sebep sonucunda engellenen veya geciken yükümlülüklerinden dolayı sorumlu tutulamaz ve bu durum işbu Kullanıcı Sözleşmesi’nin bir ihlali olarak kabul edilemez.
5.7. İşbu Kullanıcı Sözleşmesi münhasıran Türkiye Cumhuriyeti kanunlarına tabi olacaktır. İşbu Kullanıcı Sözleşmesi’nden kaynaklanan veya işbu Kullanıcı Sözleşmesi ile bağlantılı olan her türlü ihtilaf, İstanbul Merkez (Çağlayan) Mahkemeleri ve İcra Müdürlükleri’nin münhasır yargı yetkisinde olacaktır.

          </p>
      </div>
      <Footer/>
  </div>
</template>

<script>
import Footer from '../components/Footer.vue';
export default {
    components: {
        Footer
    },
}
</script>

<style>

</style>